name: Go

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: stable
        check-latest: true
        cache: true
    
    - name: Install make
      run: sudo apt-get install make

    - name: Build
      run: make build

    - name: Save dockerctl executable
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: dockerctl-exe
        path: cmd/dockerctl/dockerctl
        retention-days: 1
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: download dockerctl executable
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: dockerctl-exe
          path: cmd/dockerctl
      
      - name: make artifact executable
        run: sudo chmod +x ./cmd/dockerctl/dockerctl

      - name: check docker engine
        run: docker version
      
      - name: Install make socat
        run: sudo apt-get install make socat

      - name: Expose Docker engine
        run: make expose-docker

      - name: run tests
        run: ./tests/main.sh
